### ISSUE TITLE
Unbale to install due dependency issues

### ISSUE THREAD

**Issue by yayas87** [itseasy21/w3tools-varnish#2]
Hi,

How to fix these issues

root@spike [/]#  cd /root
root@spike [~]# chmod +x varnish-install.sh
root@spike [~]# ./varnish-install.sh
----------------------------------------
     W3TooLS Varnish Installer
              Version 0.2
     http://www.w3tool.blogspot.in/
----------------------------------------
Loaded plugins: fastestmirror, tsflags, universal-hooks
Setting up Install Process
Loading mirror speeds from cached hostfile
 * EA4: 67.222.0.10
 * base: mirror.tngwebhost.com
 * epel: fedora-epel.mirror.lstn.net
 * extras: centos.den.host-engine.com
 * ius: dfw.mirror.rackspace.com
 * remi-safe: mirrors.mediatemple.net
 * updates: mirror.sesp.northwestern.edu
Package 2:vim-enhanced-7.4.629-5.el6.x86_64 already installed and latest version
Package wget-1.12-5.el6_6.1.x86_64 already installed and latest version
Package lynx-2.8.6-27.el6.x86_64 already installed and latest version
Package sed-4.2.1-10.el6.x86_64 already installed and latest version
Package rpm-4.8.0-47.el6.x86_64 already installed and latest version
Nothing to do
Searching for cPanel ..[  cPanel Found  ]

Checking for Yum ..[  Found  ]
Checking for SED ..[  Found  ]
Loaded plugins: fastestmirror, tsflags, universal-hooks
Setting up Remove Process
No Match for argument: varnish
Loading mirror speeds from cached hostfile
 * EA4: 67.222.0.10
 * base: mirror.tngwebhost.com
 * epel: fedora-epel.mirror.lstn.net
 * extras: centos.den.host-engine.com
 * ius: dfw.mirror.rackspace.com
 * remi-safe: mirrors.mediatemple.net
 * updates: mirror.sesp.northwestern.edu
Package(s) varnish available, but not installed.
No Packages marked for removal
HTTP/1.0 200 OK
Connection: close
Server: whostmgr/11.52.1.3
Content-type: text/html; charset=utf-8

info [rebuildhttpdconf] Missing owner for domain spike.zaliyo.co.uk, force lookup to root
Built /usr/local/apache/conf/httpd.conf OK
        package varnish-release-4.1-2.el7.noarch (which is newer than varnish-release-3.0-1.el6.noarch) is already installed
Loaded plugins: fastestmirror, tsflags, universal-hooks
Setting up Install Process
Loading mirror speeds from cached hostfile
 * EA4: 67.222.0.10
 * base: mirror.tngwebhost.com
 * epel: fedora-epel.mirror.lstn.net
 * extras: centos.den.host-engine.com
 * ius: dfw.mirror.rackspace.com
 * remi-safe: mirrors.mediatemple.net
 * updates: mirror.sesp.northwestern.edu
Resolving Dependencies
--> Running transaction check
---> Package varnish.x86_64 0:4.1.0-1.el7 will be installed
--> Processing Dependency: varnish-libs = 4.1.0-1.el7 for package: varnish-4.1.0-1.el7.x86_64
--> Processing Dependency: libvarnishapi.so.1(LIBVARNISHAPI_1.1)(64bit) for package: varnish-4.1.0-1.el7.x86_64
--> Processing Dependency: systemd-units for package: varnish-4.1.0-1.el7.x86_64
--> Processing Dependency: systemd-sysv for package: varnish-4.1.0-1.el7.x86_64
--> Processing Dependency: libc.so.6(GLIBC_2.14)(64bit) for package: varnish-4.1.0-1.el7.x86_64
--> Processing Dependency: libvarnishapi.so.1(LIBVARNISHAPI_1.3)(64bit) for package: varnish-4.1.0-1.el7.x86_64
--> Processing Dependency: libvarnishapi.so.1(LIBVARNISHAPI_1.2)(64bit) for package: varnish-4.1.0-1.el7.x86_64
--> Processing Dependency: libvarnishapi.so.1(LIBVARNISHAPI_1.0)(64bit) for package: varnish-4.1.0-1.el7.x86_64
--> Processing Dependency: libvarnishapi.so.1(LIBVARNISHAPI_1.4)(64bit) for package: varnish-4.1.0-1.el7.x86_64
--> Processing Dependency: libpcre.so.1()(64bit) for package: varnish-4.1.0-1.el7.x86_64
--> Processing Dependency: libvgz.so()(64bit) for package: varnish-4.1.0-1.el7.x86_64
--> Processing Dependency: libvarnish.so()(64bit) for package: varnish-4.1.0-1.el7.x86_64
--> Processing Dependency: libvarnishcompat.so()(64bit) for package: varnish-4.1.0-1.el7.x86_64
--> Processing Dependency: libvarnishapi.so.1()(64bit) for package: varnish-4.1.0-1.el7.x86_64
--> Processing Dependency: libvcc.so()(64bit) for package: varnish-4.1.0-1.el7.x86_64
--> Running transaction check
---> Package varnish.x86_64 0:4.1.0-1.el7 will be installed
--> Processing Dependency: systemd-units for package: varnish-4.1.0-1.el7.x86_64
--> Processing Dependency: systemd-sysv for package: varnish-4.1.0-1.el7.x86_64
--> Processing Dependency: libc.so.6(GLIBC_2.14)(64bit) for package: varnish-4.1.0-1.el7.x86_64
--> Processing Dependency: libpcre.so.1()(64bit) for package: varnish-4.1.0-1.el7.x86_64
---> Package varnish-libs.x86_64 0:4.1.0-1.el7 will be installed
--> Processing Dependency: libc.so.6(GLIBC_2.14)(64bit) for package: varnish-libs-4.1.0-1.el7.x86_64
--> Processing Dependency: libpcre.so.1()(64bit) for package: varnish-libs-4.1.0-1.el7.x86_64
--> Finished Dependency Resolution
Error: Package: varnish-libs-4.1.0-1.el7.x86_64 (varnish-4.1)
           Requires: libc.so.6(GLIBC_2.14)(64bit)
Error: Package: varnish-4.1.0-1.el7.x86_64 (varnish-4.1)
           Requires: systemd-units
Error: Package: varnish-4.1.0-1.el7.x86_64 (varnish-4.1)
           Requires: libpcre.so.1()(64bit)
Error: Package: varnish-4.1.0-1.el7.x86_64 (varnish-4.1)
           Requires: libc.so.6(GLIBC_2.14)(64bit)
Error: Package: varnish-libs-4.1.0-1.el7.x86_64 (varnish-4.1)
           Requires: libpcre.so.1()(64bit)
Error: Package: varnish-4.1.0-1.el7.x86_64 (varnish-4.1)
           Requires: systemd-sysv
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
sed: can't read ./varnish: No such file or directory
./varnish-install.sh: line 73: cd: /etc/varnish/: No such file or directory
sed: can't read ./default.vcl: No such file or directory
sed: can't read ./default.vcl: No such file or directory
error reading information on service varnish: No such file or directory
varnish: unrecognized service
---------------------------------------------------
      Varnish Cache Installation Complete

If varnish failed to install or you faced any bugs feel free to post them with install log at  http://bit.ly/w3tools-varnish-issues

You can monitor varnish cache through this monitoring tool: varnishstat

Thanks for using our Varnish Installer for CPanel
For more stay tuned at our blog :  http://www.w3tool.blogspot.in/
---------------------------------------------------
root@spike [~]# varnishstat
-bash: varnishstat: command not found
root@spike [~]#

**Comment by itseasy21** [comment]
try
> yum install systemd-sysv

and then re run the installer
